test:
  gpus: 1
  log_level: "info"
  batch_size: 64
  evaluation_frequency: 2
  early_stop_tolerance: 10
  val_set_size: 0.2
  training_epochs: 1000
  overwrite_models: False
  use_cached_files: True
  seed: 0
  deterministic: True

attacks:
  activethief:
    selection_strategy: "entropy"
    budget: 1000
    iterations: 10
    training_epochs: 1000
    initial_seed_size: 2000
    output_type: "one_hot"

  cloudleak:
    adversial_strategy: "pgd"
    set_size: 200
    augmentation_multiplier: 5
    iterations: 10
    output_type: "one_hot"
