test:
  name: "test_run"
  log_level: "info"
  batch_size: 64
  evaluation_frequency: 2
  early_stop_tolerance: 10
  overwrite_models: False
  use_cached_files: True
  seed: 0

attacks:
  activethief:
    selection_strategy: "entropy"
    k: 1500
    iterations: 10
    training_epochs: 1000
    initial_seed_size: 2000
    one_hot_output: True

  copycat:
    method: "npd+pd"
    training_epochs: 1000
