test:
  gpus: 1
  log_level: "info"
  batch_size: 64
  evaluation_frequency: 2
  early_stop_tolerance: 10
  overwrite_models: False
  use_cached_files: True
  seed: 0

attacks:
  activethief:
    selection_strategy: "entropy"
    k: 1500
    iterations: 10
    training_epochs: 1000
    initial_seed_size: 2000
    output_type: "one_hot"
    val_set_size: 0.2

  cloudleak:
    adversial_strategy: "pgd"
    set_size: 200
    augmentation_multiplier: 5
    iterations: 10
    training_epochs: 1000
    output_type: "one_hot"

  copycat:
    training_epochs: 1000
    val_set_size: 0.2
